#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

$app = new \Alexecus\Spawner\App\Application();

$app->definition(__DIR__ . '/Form/definition.yml', __DIR__);
// $app->add(\Alexecus\Example\Form\FormGenerator::class);

$app->run();
