#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

$app = new \Alexecus\Spawner\App\Application();

$app->setRoot(__DIR__);

$app->definition('Form/definition.yml');
// $app->add(\Alexecus\Example\Form\FormGenerator::class);

$app->run();
