#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

$app = new \Alexecus\Spawner\Application();

$app->setRoot(__DIR__);

$app->add(\Alexecus\Example\Form\FormGenerator::class);

$app->run();
